version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/pipeline"
    schedule:
      interval: weekly
    groups:
      pipeline-python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
