// Explicit creative staging assignments; canonical identity is checked separately.
// These are new art briefs, not copied original tile maps or researched floor layouts.
export const dungeonAssignments = [
 ['tiny-woods','forest',['broadleaf-tree','fern-cluster','flower-patch'],'#fff1c8','Sunlit small woodland, a low root opening and a clear rescue clearing.'],
 ['thunderwave-cave','cave',['crystal-cluster','stalagmite-cluster'],'#d9e7ef','Cool slate corridor with sparse turquoise mineral clusters.'],
 ['mt-steel','cave',['basalt-organ','boulder-cluster'],'#e4d6ca','Exposed layered rock terraces with a wide summit silhouette.'],
 ['sinister-woods','forest',['root-arch','mushroom-ring','fallen-log'],'#b8c3bd','Dense blue-green roots, fallen timber and a darker canopy.'],
 ['silent-chasm','cave',['stone-arch','boulder-cluster'],'#d7d0bb','Eroded rock chasm framing a distant sky opening.'],
 ['mt-thunder','storm',['conducting-coil','basalt-organ','crystal-cluster'],'#cedbed','Storm summit with wind-cut basalt and restrained gold minerals.'],
 ['great-canyon','desert',['sandstone-fin','broken-pillar'],'#f4d5a6','Warm layered canyon walls and a clear high overlook.'],
 ['lapis-cave','crystal',['crystal-cluster','stone-arch'],'#b9d8ea','Blue mineral passage with restrained luminous crystal groups.'],
 ['mt-blaze','volcano',['obsidian-spire','sandstone-fin'],'#e6bc98','Open scorched mountain ascent, ash shelves and fiery horizon.'],
 ['frosty-forest','snow',['snow-pine','snow-drift'],'#e1f2f4','Snow-heavy forest leading to a pale sheltered grotto.'],
 ['mt-freeze','snow',['ice-shard','stone-arch','snow-drift'],'#eaf3fa','Cold exposed mountain ledges with ice fins and summit arch.'],
 ['uproar-forest','forest',['broadleaf-tree','fallen-log','fern-cluster'],'#e5e0ae','Warm busy forest, broad roots and broken fallen branches.'],
 ['magma-cavern','volcano',['basalt-organ','lava-vent','obsidian-spire'],'#d1c4b9','Deep basalt chamber, bounded lava channels and massive vertical organ walls.'],
 ['sky-tower','sky',['carved-pillar','floating-island','stone-arch'],'#f4ecd0','Ancient pale terrace towers surrounded by cloud banks.'],
 ['rock-path','cave',['boulder-cluster','stalagmite-cluster'],'#ddcbb7','Short rough-rock passage with low ledges.'],
 ['snow-path','snow',['snow-drift','ice-shard'],'#d8eaf0','Quiet snow route with open foreground and low ice ridges.'],
 ['howling-forest','forest',['pine-tree','root-arch','mushroom-ring'],'#b9d3bf','Tall trunks, mossy root openings and a dim green clearing.'],
 ['stormy-sea','coast',['coral-fan','broken-pillar','waterfall-rock'],'#a6d3d8','Deep turquoise ocean stone, coral and water-framed chamber.'],
 ['silver-trench','coast',['stone-arch','broken-pillar','coral-fan'],'#c3ddea','Pale monumental undersea archways in a blue-depth haze.'],
 ['meteor-cave','crystal',['crystal-cluster','basalt-organ'],'#c8b8dc','Angular violet impact minerals and dark meteor-like rock clusters.'],
 ['fiery-field','volcano',['lava-vent','sandstone-fin'],'#edc5a0','Red-brown open ash field and separated thermal vents.'],
 ['lightning-field','storm',['conducting-coil','crystal-cluster'],'#dde1b6','Charged meadow stones beneath blue storm light.'],
 ['northwind-field','snow',['snow-drift','snow-pine'],'#cfe9ef','Wind-smoothed pale meadow with sparse snowy trees.'],
 ['mt-faraway','sky',['broken-pillar','rune-plinth','cloud-bank'],'#f2d5ac','High warm summit terrace with distant clouds and a focal plinth.'],
 ['western-cave','cave',['stone-arch','basalt-organ','stalagmite-cluster'],'#c1cbd6','Broad severe rock chamber with long cool depth and high ledges.'],
 ['northern-range','cave',['boulder-cluster','stone-arch'],'#d6dfc8','Open northern rock range with pale stone saddles.'],
 ['pitfall-valley','forest',['root-arch','broadleaf-tree','fallen-log'],'#b7cfad','Steep green valley with rooted slopes and a bright opening.'],
 ['buried-relic','ruins',['stone-arch','carved-pillar','rune-plinth'],'#ded2b2','Deep ancient masonry with separated stone, ice and metal-themed chambers.'],
 ['wish-cave','crystal',['rune-plinth','crystal-cluster'],'#d6c8e8','Quiet violet mineral passage with small star-like plinth accents.'],
 ['murky-cave','cave',['mossy-rock','stone-arch'],'#b8c5b9','Damp subdued green rock and a sheltered judgment clearing.'],
 ['desert-region','desert',['cactus','sandstone-fin','fossil-ribs'],'#f5dfad','Dunes, dry plants, exposed ribs and eroded sandstone fins.'],
 ['southern-cavern','cave',['stalagmite-cluster','basalt-organ'],'#ded1be','Warm layered subterranean rock with sparse low mineral details.'],
 ['wyvern-hill','forest',['pine-tree','boulder-cluster'],'#d3debc','Open green hill terraces with large perimeter stones.'],
 ['solar-cave','crystal',['carved-pillar','rune-plinth','crystal-cluster'],'#e5ddb2','Warm shafts through cool mineral stone and low carved platforms.'],
 ['darknight-relic','ruins',['broken-pillar','stone-arch','rune-plinth'],'#adb3cd','Moon-cool ruined columns and dark recesses with readable paths.'],
 ['grand-sea','coast',['coral-fan','shell-cluster','reed-bed'],'#b5ded2','Broad green-blue coastal stone and open water edges.'],
 ['waterfall-pond','forest',['waterfall-rock','reed-bed','mossy-rock'],'#cbe7c2','Fresh mossy pond margins and a stepped rock cascade.'],
 ['unown-relic','ruins',['carved-pillar','rune-plinth','broken-pillar'],'#dbd1b3','Pale carved chambers; original abstract markings, no copied glyphs.'],
 ['joyous-tower','sky',['carved-pillar','hanging-banner','stone-arch'],'#e8e4c8','Bright vertical terrace architecture and soft cloud depth.'],
 ['far-off-sea','coast',['stone-arch','coral-fan','shell-cluster'],'#abcbd8','Remote cool sea margins and worn underwater arch fragments.'],
 ['purity-forest','forest',['broadleaf-tree','flower-patch','root-arch'],'#e2edc5','Soft luminous mature woodland and an uncluttered final clearing.'],
 ['oddity-cave','cave',['crystal-cluster','mossy-rock','fossil-ribs'],'#d4c4de','Mixed mineral rock with unusual low color accents.'],
 ['remains-island','ruins',['broken-pillar','fern-cluster','root-arch'],'#d8dfbf','Weathered island masonry reclaimed by green roots.'],
 ['marvelous-sea','coast',['coral-fan','shell-cluster','waterfall-rock'],'#c6e3d9','Clear warm reef colors and small shoreline cascades.'],
 ['fantasy-strait','coast',['stone-arch','broadleaf-tree','reed-bed'],'#d5e4ed','Pale water passage between worn rock arches and distant islands.'],
];
export const dojoAssignments = [
 ['normal','#e9dec1','training-post'],['fire','#efc09a','hanging-banner'],['water','#bbdbe5','conducting-coil'],['grass','#cadfb4','training-post'],['electric','#ebe1a2','conducting-coil'],['ice','#dae9f0','carved-pillar'],['fighting','#dfb491','training-post'],['ground','#e2c99c','stone-arch'],['flying','#d5e2de','hanging-banner'],['psychic','#dec4e8','carved-pillar'],['poison','#c5b6db','hanging-banner'],['bug','#cddcad','training-post'],['rock','#d1c5b3','stone-arch'],['ghost','#bfbacf','hanging-banner'],['dragon','#b8cfd4','carved-pillar'],['dark','#acb4c5','stone-arch'],['steel','#c6d2d3','conducting-coil'],['team-shifty','#c3d3ae','training-post'],['team-constrictor','#d8c9e4','hanging-banner'],['team-hydro','#badce6','conducting-coil'],['team-rumblerock','#d9c2a5','stone-arch'],['rescue-team','#ecd79e','timber-gate'],
];
export const friendAssignments = [
 ['beau-plains','forest',['flower-patch','broadleaf-tree'],'#e8e8b4','Flower-rich open grassland with gentle edge trees.'],
 ['mt-cleft','cave',['stone-arch','boulder-cluster'],'#d1c4b3','A split rock ridge framing an open resting shelf.'],
 ['turtleshell-pond','coast',['shell-cluster','reed-bed'],'#c8dfbf','Sheltered shallow pond with shell-like low rock islands.'],
 ['mist-rise-forest','forest',['pine-tree','mushroom-ring'],'#bfd8ce','Tall damp trees and a misty low moss floor.'],
 ['flyaway-forest','forest',['broadleaf-tree','fallen-log'],'#dce5ba','Open canopy gaps and high branching roost trees.'],
 ['wild-plains','forest',['fern-cluster','boulder-cluster'],'#dbd0a0','Open rough grass with sparse rocks and a wide horizon.'],
 ['ravaged-field','volcano',['basalt-organ','obsidian-spire'],'#ccb79f','Scorched barren field with fractured dark stones.'],
 ['energetic-forest','forest',['flower-patch','fallen-log'],'#e8dba6','Sunny young woodland with warm flowers and playful log forms.'],
 ['furnace-desert','desert',['sandstone-fin','cactus'],'#f0c699','Hot ochre sand basin and heat-darkened rock fins.'],
 ['safari','forest',['broadleaf-tree','fern-cluster'],'#d9d39b','Broad dry grassland with isolated spreading shade trees.'],
 ['mt-moonview','cave',['boulder-cluster','stone-arch'],'#c2c8e0','Pale moon-facing mountain terrace and a sheltered rock arch.'],
 ['darkness-ridge','storm',['basalt-organ','sandstone-fin'],'#b9bfd2','Dark high ridgeline and wind-cut stone silhouettes.'],
 ['sky-blue-plains','forest',['flower-patch','fern-cluster'],'#d5ebde','Cool open meadow with blue-flower accents and low plants.'],
 ['echo-cave','cave',['stone-arch','stalagmite-cluster'],'#d6dedb','Hollow chamber arches and spaced echoing stone towers.'],
 ['jungle','forest',['root-arch','broadleaf-tree','fern-cluster'],'#b9cc9f','Dense broadleaf canopy, thick roots and large fern margins.'],
 ['mushroom-forest','forest',['mushroom-ring','fallen-log'],'#d9c5d0','Low mushroom glades around soft fallen timber.'],
 ['secretive-forest','forest',['root-arch','mushroom-ring'],'#b2c2bd','Enclosed dim woodland with small concealed root alcoves.'],
 ['boulder-cave','cave',['boulder-cluster','basalt-organ'],'#d3ccbc','Heavy rounded boulder banks and low stone shelves.'],
 ['scorched-plains','volcano',['lava-vent','basalt-organ'],'#dcbd9e','Dry heated plain with isolated safe thermal-rock features.'],
 ['tadpole-pond','coast',['reed-bed','mossy-rock'],'#c5ddbc','Small warm pond with reed beds and low moss stones.'],
 ['decrepit-lab','ruins',['lab-table','conducting-coil','broken-pillar'],'#c8d5d4','Abandoned masonry laboratory with weathered tables and inert coils.'],
 ['mt-discipline','dojo',['training-post','stone-arch'],'#d6c9ac','Open rock training terrace with timber practice posts.'],
 ['bountiful-sea','coast',['coral-fan','shell-cluster'],'#d1e6c5','Rich shallow reef garden with warm coral groups.'],
 ['mt-deepgreen','forest',['pine-tree','mossy-rock'],'#bbd2ae','Deep-green wooded mountain ledges and mossy stones.'],
 ['power-plant','storm',['conducting-coil','lab-table'],'#c7d4df','Weathered industrial stone enclosure with inert ceramic coil structures.'],
 ['ice-floe-beach','snow',['snow-drift','shell-cluster'],'#d9edf0','Pale beach margins with low ice floes and shells.'],
 ['poison-swamp','forest',['reed-bed','mushroom-ring'],'#c2bad2','Violet-tinted wetland margins, reeds and low fungus islands.'],
 ['shallow-beach','coast',['shell-cluster','reed-bed'],'#f0e1bd','Warm shallow sand and scattered shells beside bright water.'],
 ['treasure-sea','coast',['broken-pillar','shell-cluster'],'#eadbad','Submerged old stone fragments and pearl-colored shell beds.'],
 ['rub-a-dub-river','forest',['waterfall-rock','reed-bed'],'#d1e7d1','Flowing river banks with reeds and rounded stone steps.'],
 ['overgrown-forest','forest',['root-arch','fern-cluster'],'#bccba0','Root-dense ancient woodland with thick low plants.'],
 ['frigid-cavern','snow',['ice-shard','stone-arch'],'#caddeb','Cold sheltered ice chamber with angular side crystals.'],
 ['crater','volcano',['obsidian-spire','basalt-organ'],'#c9b6b2','A dark impact basin with broken volcanic-looking rim stones.'],
 ['waterfall-lake','coast',['waterfall-rock','mossy-rock'],'#cae7dc','Tall rock cascade meeting a broad calm lake.'],
 ['mystic-lake','coast',['stone-arch','coral-fan'],'#d0cde5','Quiet violet-blue lake framed by pale reflective stone arches.'],
 ['transform-forest','forest',['broadleaf-tree','mushroom-ring','flower-patch'],'#d5d8be','Mixed canopy glade with varied low growth and soft colors.'],
 ['deep-sea-floor','coast',['coral-fan','boulder-cluster'],'#a9c8d9','Deep blue seafloor shelf and spaced low coral.'],
 ['ancient-relic','ruins',['carved-pillar','rune-plinth'],'#d8cfb2','Old carved chamber centered on a low ceremonial plinth.'],
 ['legendary-island','sky',['carved-pillar','rune-plinth','cloud-bank'],'#e2d8bf','High isolated island terrace with three open perches.'],
 ['cryptic-cave','crystal',['rune-plinth','stalagmite-cluster'],'#c9bddb','Quiet mineral alcove with original abstract geometric carvings.'],
 ['final-island','forest',['broadleaf-tree','flower-patch','mossy-rock'],'#e8e2c2','Small serene island glade with soft flowers and one mature tree.'],
 ['thunder-meadow','storm',['crystal-cluster','pine-tree'],'#d9dcae','Open wind-swept meadow with gold mineral accents.'],
 ['peanut-swamp','forest',['reed-bed','fallen-log'],'#d3ceac','Warm muddy wetland with reeds and low curved fallen wood.'],
 ['aged-chamber-an','ruins',['carved-pillar','rune-plinth'],'#d4c59e','Warm aged masonry room; no copied Unown glyph textures.'],
 ['aged-chamber-o-question','ruins',['broken-pillar','stone-arch'],'#bdc8d0','Cool worn companion chamber with fractured columns and arch.'],
 ['serene-sea','coast',['shell-cluster','coral-fan'],'#d8ece1','Pale calm shallow reef with broad empty water margins.'],
 ['sacred-field','forest',['flower-patch','root-arch'],'#e9dcae','Warm ceremonial meadow framed by graceful living roots.'],
 ['deep-sea-current','coast',['waterfall-rock','coral-fan'],'#b5cfe0','Deep current channel with tall side rocks and blue coral.'],
 ['rainbow-peak','sky',['rune-plinth','floating-island'],'#ecd6b0','Warm summit perch with multicolored distant mineral accents.'],
 ['healing-forest','forest',['flower-patch','broadleaf-tree'],'#deedc9','Gentle luminous woodland clearing with rich flowering margins.'],
 ['dragon-cave','cave',['stone-arch','fossil-ribs'],'#c6cfca','Large vaulted rock shelter with old pale fossil ribs.'],
 ['magnetic-quarry','storm',['conducting-coil','basalt-organ'],'#c0ced6','Angular mineral quarry and inert magnetic-looking stone/coil motifs.'],
 ['southern-island','coast',['broadleaf-tree','shell-cluster'],'#eddcbd','Warm sandy island edge with a spreading shade tree.'],
 ['seafloor-cave','coast',['stone-arch','waterfall-rock'],'#b1d2d4','Blue grotto opening onto water and low marine growth.'],
 ['volcanic-pit','volcano',['lava-vent','obsidian-spire'],'#d6bca6','Deep bounded thermal basin with tall obsidian perimeter fins.'],
 ['stratos-lookout','sky',['floating-island','carved-pillar','cloud-bank'],'#d9e6ed','High pale lookout terrace above soft cloud depth.'],
 ['enclosed-island','ruins',['stone-arch','root-arch'],'#cdd7bb','Sheltered island ruin ring with rooted stone entrances.'],
];
