/** Prospective escort owner types. These declarations do not admit a save or
 * activate a campaign; the successor must independently prove its raw owners.
 * @typedef {import('./campaign.js').SessionActor} Actor
 * @typedef {{jobId:import('../contracts.js').JobId,client:import('./campaign.js').SpeciesForm,recipient:import('./campaign.js').SpeciesForm,slot:number,nativeRecruitedId:number,joinLocation:number,joinFloor:number,level:number,totalExperience:number,stats:import('./campaign.js').StatBlock,iqPoints:number,iqSkillIds:readonly string[],tacticId:string,isLeader:boolean,heldItem:null,belly:number,maxBelly:number,hiddenPower:{nativeTypeId:number,power:number},moves:readonly {moveId:string,nativeMoveId:number,basePp:number,enabled:boolean,currentPp:number,powerBoost:number,ppCapacityBonus:number}[],beforeGeneralRandom:import('../domain/native-general-rng.js').NativeGeneralRandomState,afterGeneralRandom:import('../domain/native-general-rng.js').NativeGeneralRandomState}} PreparedGuest
 * @typedef {{kind:'escort-guest',jobId:import('../contracts.js').JobId}} EscortGuestBinding
 * @typedef {Omit<Actor,'binding'> & {binding:EscortGuestBinding}} EscortGuestActor
 * @typedef {{actorId:import('../contracts.js').ActorId,jobId:import('../contracts.js').JobId,slot:number,nativeRecruitedId:number,joinLocation:number,joinFloor:number,client:import('./campaign.js').SpeciesForm,recipient:import('./campaign.js').SpeciesForm,hiddenPower:{nativeTypeId:number,power:number},moveSlotIds:import('../contracts.js').MoveSlotId[],heldContainerId:import('../contracts.js').ContainerId}} EscortGuestEntry
 * @typedef {{policyId:'native-general-prospective-conversions-and-pickup-v1',adoptedRevision:number,generalRandom:import('../domain/native-general-rng.js').NativeGeneralRandomState}} EscortRuntime
 * @typedef {{input:import('../domain/gameplay/native-escort-entry.js').EntryInput,result:ReturnType<typeof import('../domain/gameplay/native-escort-entry.js').prepareNativeEscortEntry>,guest:EscortGuestEntry|null,construction:EscortConstructionRecord|null,objective:EscortObjectiveReceipt|null,pickup:EscortPickupReceipt[]}} NativeEscortConversion
 * @typedef {{actor:EscortGuestActor,entry:EscortGuestEntry,container:import('./campaign.js').ItemContainer,sessionId:import('../contracts.js').SessionId,witness:import('./escort-construction.js').EscortConstructionWitness,allocationMark:number}} EscortConstructionRecord
 * @typedef {{beforeGuest:EscortGuestActor,beforeRecipient:Actor,floor:import('./campaign.js').FloorState,sourceFrame:import('./campaign.js').TurnContinuation,completedRevision:number,recipientSlot:number,resetJoinLocation:number}} EscortObjectiveReceipt
 * @typedef {{actorId:import('../contracts.js').ActorId,slot:number,mapId:import('../contracts.js').MapId,floorId:import('../contracts.js').FloorId,revision:number,beforeDungeonRandom:import('../contracts.js').RandomState,afterDungeonRandom:import('../contracts.js').RandomState,beforeGeneralRandom:import('../domain/native-general-rng.js').NativeGeneralRandomState,afterGeneralRandom:import('../domain/native-general-rng.js').NativeGeneralRandomState,itemId:import('../contracts.js').ItemId,item:import('./campaign.js').ItemInstance|null}} EscortPickupReceipt
 * @typedef {{x:number,z:number}} EscortTargetPosition
 * @typedef {{mapId:import('../contracts.js').MapId,objective:'stand'|'chase'|'remembered'|'roam'|'leave-room'|'run-away',target:{ref:import('./campaign.js').ActorSlotRef,mapId:import('../contracts.js').MapId}|null,targetPosition:EscortTargetPosition,notNextToTarget:boolean,targetingEnemy:boolean,turningAround:boolean,allySkip:boolean,recalculateFollow:boolean,waiting:boolean,moveRandomly:boolean,mobileTurnTimer:number}} EscortNativeAi
 * @typedef {{positions:[import('../contracts.js').GridPosition,import('../contracts.js').GridPosition,import('../contracts.js').GridPosition,import('../contracts.js').GridPosition],lastWalk:{before:[import('../contracts.js').GridPosition,import('../contracts.js').GridPosition,import('../contracts.js').GridPosition,import('../contracts.js').GridPosition],from:import('../contracts.js').GridPosition,to:import('../contracts.js').GridPosition,invisible:boolean,revision:number}|null}} EscortPositionHistory
 * @typedef {{mapId:import('../contracts.js').MapId,members:Record<import('../contracts.js').ActorId,EscortPositionHistory>}} EscortTeamHistory
 * @typedef {{phase:'recipient'|'return',origin:import('./move-learning.js').LearningOrigin,actorOrder:import('../contracts.js').ActorId[],actorIndex:number,createdRevision:number,resumeFrameFingerprint:string,schedulerTag:{kind:'ready'}|{kind:'scene-paused',sceneInstanceId:import('./campaign.js').SceneInstanceId}}} EscortLearningWork
 * @typedef {{entry:EscortGuestEntry,ai:EscortNativeAi|null,lossNoticeRevision:number|null,joinLocation:number,nativeRecruitedId:number,lifecycle:{kind:'live'}|{kind:'removed',reason:'objective'|'fainted',removedRevision:number,mapId:import('../contracts.js').MapId,source:import('./campaign.js').ActorSlotRef}}} EscortGuestRuntime
 */
export {};
