// Static data/source projection only. Never import or evaluate game modules.
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';

const root = new URL('../../../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
const authoring = 'tools/pokemon-dungeon/content/item-ai/';
const bytes = await read(authoring + 'facts.json');
const facts = JSON.parse(bytes);
const nativeBytes = await read(authoring + 'native-item-data.json');
const native = JSON.parse(nativeBytes);
const hash = value => createHash('sha256').update(value).digest('hex');
assert.equal(facts.schemaVersion, 1);
assert.equal(facts.repository, 'pret/pmd-red');
assert.equal(facts.commit, '6bcbec4f906938c0243aa2026bcbd41b577bab85');
assert.equal(facts.qualification, 'pinned-red-comparative-not-blue-binary-proof');
assert.deepEqual(facts.flagOrder, ['self-use', 'ally-throw', 'enemy-throw']);
assert.equal(facts.sourceFiles[0].path, 'data/item/item_data.json');
assert.equal(hash(nativeBytes), facts.sourceFiles[0].sha256);
assert.deepEqual(facts.sourceFiles.map(row => row.path), ['data/item/item_data.json', 'tools/dungeonjson/dungeonjson.cpp', 'include/structs/str_items.h', 'include/constants/item.h']);
for (const source of facts.sourceFiles) assert.match(source.sha256, /^[a-f0-9]{64}$/);
assert.deepEqual(facts.zeroDefaultEvidence, { path: 'tools/dungeonjson/dungeonjson.cpp', readArrayLines: [666, 680], emitItemLines: [751, 774] });
assert.deepEqual(facts.flagOrderEvidence, { path: 'include/structs/str_items.h', lines: [7, 24] });
const categories = ['thrown_line', 'thrown_arc', 'berries_seeds_vitamins', 'food_gummies', 'held_items', 'tms_hms', 'poke', 'category_7', 'other', 'orbs', 'link_box', 'used_tm'];
const existing = (await Promise.all([1, 2, 3, 4].map(async n => JSON.parse(await read(`tools/pokemon-dungeon/content/effects-runtime/items-0${n}.json`)).records))).flat();
assert.equal(existing.length, 240);
assert.equal(new Set(existing.map(row => row.internalId)).size, 240);
assert.equal(new Set(existing.map(row => row.id)).size, 240);
assert.equal(native.length, 240);
assert.equal(facts.records.length, 240);
assert.equal(facts.records.filter(row => row.aiFlagsOrigin === 'explicit').length, 43);
assert.equal(facts.records.filter(row => row.aiFlagsOrigin === 'assembler-default-zero').length, 197);
for (const [id, row] of facts.records.entries()) {
  const source = native[id], item = existing.find(candidate => candidate.internalId === id);
  assert.deepEqual(Object.keys(row).sort(), ['actionType', 'aiFlags', 'aiFlagsOrigin', 'category', 'itemId', 'nativeId', 'sourceName', 'spawnStackRange']);
  assert.equal(row.nativeId, id);
  assert.equal(row.itemId, item.id);
  assert.equal(row.sourceName, source.name);
  assert.equal(row.category, source.category.slice('CATEGORY_'.length).toLowerCase());
  assert.ok(categories.includes(row.category));
  assert.equal(row.category, item.category);
  assert.equal(row.actionType, source.actionType);
  assert.equal(row.actionType, item.actionType);
  assert.deepEqual(row.spawnStackRange, source.spawnAmountRange ?? null);
  assert.deepEqual(row.spawnStackRange, item.spawnStackRange);
  assert.equal(row.aiFlags.length, 3);
  assert.ok(row.aiFlags.every(flag => typeof flag === 'boolean'));
  assert.deepEqual(row.aiFlags, source.aiFlags ?? [false, false, false]);
  assert.equal(row.aiFlagsOrigin, source.aiFlags === undefined ? 'assembler-default-zero' : 'explicit');
}
const rows = facts.records.map(({ nativeId, itemId, category, aiFlags, aiFlagsOrigin }) => ({ nativeId, itemId, category, aiFlags, aiFlagsOrigin }));
const output = `// Generated by export-item-ai.mjs; pinned original Red comparative, not Blue binary proof.
// Authoring SHA-256: ${hash(bytes)}; provenance: ${authoring}facts.json.
// AI eligibility only: no Item Master/use/throw handler or command permission.
/** @type {ReadonlyArray<Readonly<{nativeId:number,itemId:string,category:string,aiFlags:readonly boolean[],aiFlagsOrigin:string}>>} */
export const NATIVE_ITEM_AI_FACTS = Object.freeze(${JSON.stringify(rows)}.map(row => Object.freeze({ ...row, aiFlags: Object.freeze(row.aiFlags) })));
export const ITEM_AI_FLAG_ORDER = Object.freeze(['self-use', 'ally-throw', 'enemy-throw']);
export const ITEM_CATEGORY_ORDER = Object.freeze(${JSON.stringify(categories)});
`;
const destination = 'games/pokemon-dungeon-reimagined/content/item-ai-facts.js';
assert(Buffer.byteLength(output) < 1048576);
if (process.argv.includes('--check')) assert.equal(await read(destination), output, 'Stale native item AI projection');
else await writeFile(new URL(destination, root), output);
console.log(`${process.argv.includes('--check') ? 'Verified' : 'Exported'} all240 item identity/category/action/stack/AI joins:43 explicit triples +197 zero defaults; no game execution.`);
