import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import path from 'node:path';

export const authoringRoot = fileURLToPath(new URL('../content/effects-runtime/', import.meta.url));
export const runtimeRoot = fileURLToPath(new URL('../../../games/pokemon-dungeon-reimagined/content/effects/', import.meta.url));
export const catalogId = 'original-blue-qualified-effect-facts';
export const encode = value => `${JSON.stringify(value)}\n`;
export const sha256 = value => createHash('sha256').update(value).digest('hex');

/** Generate JSDoc from the same closed schemas; checker never executes these types. */
function typeOf(schema) {
  if (schema.anyOf) return `(${schema.anyOf.map(typeOf).join('|')})`;
  if (schema.enum) return schema.enum.map(value => JSON.stringify(value)).join('|');
  if (schema.type === 'object') return `{${Object.entries(schema.properties).map(([key,value]) => `${JSON.stringify(key)}${schema.required.includes(key) ? '' : '?'}: ${typeOf(value)}`).join(', ')}}`;
  if (schema.type === 'array') return `Array<${typeOf(schema.items)}>`;
  return ['integer','number'].includes(schema.type) ? 'number' : schema.type;
}
const typeNames = {actions:'Action',items:'Item',statuses:'Status',timers:'Timer',families:'Family',geometries:'Geometry',categories:'Category',rules:'Rule',guards:'Guard',contracts:'Contract',terrain:'Terrain','species-parameters':'SpeciesParameters','auxiliary-effects':'AuxiliaryEffect',conflicts:'Conflict','availability-routes':'AvailabilityRoute',treasures:'Treasure',parameters:'Parameter','auxiliary-statuses':'AuxiliaryStatus'};

/** Read data only. Neither the exporter nor the checker imports game modules. */
export async function buildEffectResources() {
  const names = (await readdir(authoringRoot)).filter(name => !name.startsWith('research-') && /-\d{2}\.json$/.test(name)).sort();
  const families = {};
  const files = new Map();
  const resources = [];
  for (const name of names) {
    const data = JSON.parse(await readFile(path.join(authoringRoot, name), 'utf8'));
    if (Object.keys(data).sort().join('|') !== 'catalogId|family|records|schemaVersion' || data.schemaVersion !== 1 || data.catalogId !== catalogId || name !== `${data.family}-${name.slice(-7)}` || !Array.isArray(data.records)) throw new Error(`Invalid authoring header ${name}`);
    const text = encode(data);
    if (Buffer.byteLength(text) >= 1024 * 1024) throw new Error(`Oversize resource ${name}`);
    files.set(name, text);
    (families[data.family] ??= []).push(...data.records);
    resources.push({ file: name, family: data.family, count: data.records.length, sha256: sha256(text) });
  }
  const coverage = JSON.parse(await readFile(path.join(authoringRoot, 'coverage.json'), 'utf8'));
  const schemas = JSON.parse(await readFile(path.join(authoringRoot, 'schemas.json'), 'utf8'));
  files.set('schemas.json', encode(schemas));
  files.set('index.json', encode({ schemaVersion: 1, catalogId, resources, coverage, schemaSha256: sha256(encode(schemas)) }));
  const integrity = `// Generated by export-effects.mjs; do not edit.\nexport const EFFECT_INDEX_SHA256 = '${sha256(files.get('index.json'))}';\n`;
  const types = '// Generated by export-effects.mjs; closed factual types, no evaluation.\n' + Object.entries(typeNames).map(([key,name]) => `/** @typedef {${typeOf(schemas.families[key])}} ${name} */\n`).join('') + "/** @typedef {Omit<Action, 'id'> & {id: string, actionId: string}} Move */\nexport {};\n";
  return { families, coverage, schemas, files, integrity, types };
}

export async function exportEffectResources(check = false) {
  const { files, integrity, types } = await buildEffectResources();
  const typesFile = path.resolve(runtimeRoot, '../effects-types.js');
  if (check) { if (await readFile(typesFile, 'utf8') !== types) throw new Error('Stale effect types'); }
  else await writeFile(typesFile, types);
  const integrityFile = path.resolve(runtimeRoot, '../effects-integrity.js');
  if (check) {
    if (await readFile(integrityFile, 'utf8') !== integrity) throw new Error('Stale effect integrity anchor');
  } else await writeFile(integrityFile, integrity);
  if (!check) await mkdir(runtimeRoot, { recursive: true });
  for (const [name, expected] of files) {
    const filename = path.join(runtimeRoot, name);
    if (check) {
      const actual = await readFile(filename, 'utf8').catch(() => null);
      if (actual !== expected) throw new Error(`Stale effect export: ${name}`);
    } else await writeFile(filename, expected);
  }
  const present = (await readdir(runtimeRoot)).sort();
  if (present.join('|') !== [...files.keys()].sort().join('|')) throw new Error('Unexpected effect runtime resource; remove stale files explicitly.');
  console.log(`${check ? 'Verified' : 'Exported'} ${files.size} deterministic effect resources.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await exportEffectResources(process.argv.includes('--check'));
}
